### ISSUE TITLE
IE11用の古いテクニックを削除したい

### ISSUE THREAD

**Issue by arktds** [d-zero-dev/frontend-guidelines#142]
IE11はサポート対象外のため

https://github.com/d-zero-dev/frontend-guidelines/blob/8470d9c7f6e12c6368cde434dc5cc2c8d8778011/src/css.md?plain=1#L715-L726

**Comment by YusukeHirao** [comment]
対応済み: https://github.com/d-zero-dev/frontend-guidelines/commit/394932b923956944091c6c3cfe2933b18a7c8e80#diff-f1165ad7fd615631d6b4cd512f53c6d6c1ac50cfe665d39b9b6e410953ebf9e9L719-R739
